# Generated by Django 4.1.5 on 2023-01-15 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_title', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.groups_pay')),
            ],
        ),
    ]
